/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/types/(.*)$",
    "^@/env(.*)$",
    "^@/constants/(.*)$",
    "^@/config/(.*)$",
    "^@/i18n/(.*)$",
    "^@/services/(.*)$",
    "^@/lib/(.*)$",
    "^@/hooks/(.*)$",
    "^@/features/(.*)$",
    "^@/shared/layout/(.*)$",
    "^@/shared/components/ui/(.*)$",
    "^@/shared/components/(?!icons$)(.*)$",
    "^@/styles/(.*)$",
    "^@/app/(.*)$",
    "^@/shared/components/icons$",
    "",
    "^[./]",
  ],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
};
